### ISSUE TITLE
Is it possible to pass array to data fixture?

### ISSUE THREAD

**Issue by q-user** [theY4Kman/pytest-drf#7]
Trying to create data fixture with array included in dict  like this:

    class TestOneClickOrderView(
        APIViewTest,
        UsesPostMethod,
        Returns201
    ):
        data = lambda_fixture(lambda: {
            'phone_number': '+79781112233',
            'email': 'gde@to.yam',
            'lines': [{'id': 1, 'quantity': 2}, {'id': 2, 'quantity': 1}]
        })

But lines are coming to POST dict as a string

![Image of postdata](https://i.imgur.com/2nBpkas.png)

Is it possible to pass array data?

**Comment by theY4Kman** [comment]
Ah, yes, I really ought to include a note about this in the docs. I've been asked about this before by email.

pytest-drf uses the DRF API test client, which encodes its POST bodies as multipart, by default. This can be changed in two ways, that I'm aware of:

 - On a per-request basis, by passing `format='json'` when making the request. This can be achieved in pytest-drf by overriding/extending the `kwargs` fixture.
	  ```py
	  # with pytest-lambda
	  kwargs = lambda_fixture(lambda data, headers: {
	      'data': data,
	      'headers': headers,
	      'format': 'json',
	  })
	  
	  # with vanilla pytest
	  @pytest.fixture
	  def kwargs(self, data, headers):
	      return {
	          'data': data,
	          'headers': headers,
	         
	  ```

	I find this a little wonky, though, and chances are that you want to use JSON all the time.

 - On a permanent basis, by configuring the `TEST_REQUEST_DEFAULT_FORMAT` in the `REST_FRAMEWORK` settings. In your Django settings, set this:
	  ```py
	  # myproject/settings.py
	  
	  REST_FRAMEWORK['TEST_REQUEST_DEFAULT_FORMAT'] = 'json'
	  
	  # or
	  
	  REST_FRAMEWORK = {
	      # ...
	      'TEST_REQUEST_DEFAULT_FORMAT': 'json',
	  }
	  ```

**Comment by q-user** [comment]
Thank you!
