### ISSUE TITLE
Update UserGuide Build Libraries

### ISSUE THREAD

**Issue by jamathews** [theY4Kman/pytest-drf#9]
If we upgrade to `sphinx` 4.1 or higher we'll be able to use its built-in link checker (it was present in earlier versions but broke on the US Patent website). This _should_ be just a matter of updating the `Pipfile` and/or `Pipfile.lock`, but we need to test the Jenkins environment before breaking the build.

**Comment by theY4Kman** [comment]
FYI: for a fuller deletion, you can open the "edited" drop-down, click the revision, hit its Options drop-down, and click "Delete revision from history". I went ahead and did that ;)
